"""
Django settings for the Factory Management System (FMS).

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see:
    https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see:
    https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Base directory
# ---------------------------------------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w*to0-*9cejm84mg+b@$ji0)1l&5&hb3e6^l%wuolr!zylq=(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Third-party packages
THIRD_PARTY_APPS = [
    'rest_framework',   # Django REST Framework
    'drf_yasg',         # Swagger / OpenAPI docs
]

# Project-specific apps — each represents a bounded domain in the factory.
PROJECT_APPS = [
    'accounts.apps.AccountsConfig',    # Custom user model & authentication
    'inventory.apps.InventoryConfig',  # Finished-goods inventory
    'employees.apps.EmployeesConfig',  # Employee records
    'salary.apps.SalaryConfig',        # Salary payment records
    'sales.apps.SalesConfig',          # Sales transactions
    'reports.apps.ReportsConfig',      # Reporting (no DB models)
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS


# ---------------------------------------------------------------------------
# Custom User Model
# ---------------------------------------------------------------------------
# Must be set BEFORE the first `migrate` command is run.
# Tells Django to use accounts.User instead of the built-in auth.User.
AUTH_USER_MODEL = 'accounts.User'


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------------------------------------------------------------------
# URL configuration
# ---------------------------------------------------------------------------
ROOT_URLCONF = 'fms.urls'


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ---------------------------------------------------------------------------
# WSGI
# ---------------------------------------------------------------------------
WSGI_APPLICATION = 'fms.wsgi.application'


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
# Using SQLite for development. Switch to PostgreSQL for production.
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "fms_db",
        "USER": "root",
        "PASSWORD": "SAMriddha1",
        "HOST": "localhost",
        "PORT": "3306",
    }
}

# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'

# Use UTC internally; convert to local time only at the presentation layer.
TIME_ZONE = 'UTC'

USE_I18N = True

# Always store datetimes as timezone-aware values in the database.
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------
STATIC_URL = 'static/'


# ---------------------------------------------------------------------------
# Default primary key type
# ---------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# ---------------------------------------------------------------------------
# drf-yasg (Swagger / ReDoc)
# ---------------------------------------------------------------------------
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': True,           # Show login/logout in Swagger UI
    'SECURITY_DEFINITIONS': {
        'Basic': {'type': 'basic'},
        'Session': {'type': 'apiKey', 'in': 'cookie', 'name': 'sessionid'},
    },
}
