"""
New sales_report table: one row per sales report generated, credited to the
Admin or the Manager who ran it (at most one), with its date range
(start_date <= end_date) and totals.
"""

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_manager_created_by_admin_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Sales Count')),
                ('items_sold', models.PositiveIntegerField(default=0, verbose_name='Items Sold')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Revenue')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports', to='accounts.adminprofile', verbose_name='Generated By (Admin)')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports', to='accounts.managerprofile', verbose_name='Generated By (Manager)')),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'db_table': 'sales_report',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='sales_report_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('admin__isnull', True), ('manager__isnull', True), _connector='OR'), name='sales_report_one_role'),
        ),
    ]
