# Generated by Django 4.2.13 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('designation', models.CharField(help_text='Job title or role within the factory (e.g. Machine Operator).', max_length=100, verbose_name='Designation')),
                ('joining_date', models.DateField(help_text='The date the employee started working at the factory.', verbose_name='Joining Date')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Agreed monthly/periodic base salary for this employee.', max_digits=12, verbose_name='Base Salary')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10, verbose_name='Employment Status')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
    ]
