# Generated by Django 4.2.16 on 2026-09-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salarypayment',
            table='salary_payment',
        ),
    ]
