# Generated by Django 4.2.16 on 2026-09-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salarypayment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-id'], 'verbose_name': 'Salary Payment', 'verbose_name_plural': 'Salary Payments'},
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='payment_method',
        ),
    ]
