# Generated by Django 4.2.13 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product.', verbose_name='Description')),
                ('sku', models.CharField(help_text='Stock Keeping Unit — must be unique across all products.', max_length=100, unique=True, verbose_name='SKU')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price at which this product is sold to customers.', max_digits=12, verbose_name='Selling Price')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Current number of units available in the warehouse.', verbose_name='Quantity in Stock')),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='When quantity_in_stock falls to or below this value, the product is considered low stock.', verbose_name='Minimum Stock Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
