# Generated by Django 4.2.16 on 2026-09-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to retire this product instead of deleting it. Inactive products stay in the catalogue so past invoices remain intact, but cannot be added to new sales.', verbose_name='Active'),
        ),
    ]
