# Generated by Django 4.2.13 on 2026-08-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique identifier for this sale/invoice.', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Grand total of all line items in this invoice.', max_digits=14, verbose_name='Total Amount')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sale Date')),
                ('sold_by', models.ForeignKey(help_text='The system user who recorded this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Sold By')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of sale. Stored explicitly so historical records remain accurate if the product price changes later.', max_digits=12, verbose_name='Unit Price')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity × unit_price — computed and stored on save.', max_digits=14, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product', verbose_name='Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'ordering': ['id'],
            },
        ),
    ]
