# Generated by Django 4.2.16 on 2026-09-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='sale_item',
        ),
    ]
