# Generated by Django 4.2.16 on 2026-09-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sales', '0003_sale_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(blank=True, help_text='The customer order this invoice was raised from, if any. Walk-in sales recorded directly have no order behind them, so this is optional; if the order is later removed the invoice survives without it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='orders.order', verbose_name='Order'),
        ),
    ]
