import { useEffect, useMemo, useState } from "react";

import SalesCharts from "../../charts/SalesCharts";
import { labelDays } from "../../charts/aggregate";
import api, { getErrorMessage } from "../../services/api";

/**
 * Sales Report — generated by Admin and manager alike.
 *
 * Everything here comes from one call to /reports/sales/: the headline
 * figures, the daily series the charts plot and the per-product breakdown are
 * the same arithmetic done once on the server, so a tile can never disagree
 * with a bar. Individual invoices are not repeated here — they have their own
 * page; this report is about the period, not the paperwork.
 */

const money = (value) =>
  `Rs ${Number(value).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const longDay = (iso) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });

const EMPTY_REPORT = {
  start_date: null,
  end_date: null,
  truncated: false,
  totals: {
    sales_count: 0,
    revenue: "0.00",
    items_sold: 0,
    days: 0,
    selling_days: 0,
    average_daily_revenue: "0.00",
  },
  busiest_day: null,
  quietest_day: null,
  best_revenue_day: null,
  days_series: [],
  products: [],
};

export default function SalesReport() {
  const [report, setReport] = useState(EMPTY_REPORT);
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [filtered, setFiltered] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async (start, end) => {
    setLoading(true);
    setError("");
    try {
      const params = {};
      if (start) params.start_date = start;
      if (end) params.end_date = end;
      const { data } = await api.get("/reports/sales/", { params });
      setReport(data);
      setFiltered(Boolean(start || end));
    } catch (err) {
      setError(getErrorMessage(err));
      setReport(EMPTY_REPORT);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load("", "");
  }, []);

  const series = useMemo(
    () => labelDays(report.days_series),
    [report.days_series]
  );

  const applyFilters = (event) => {
    event.preventDefault();
    load(startDate, endDate);
  };

  const resetFilters = () => {
    setStartDate("");
    setEndDate("");
    load("", "");
  };

  const { totals } = report;

  const subtitle =
    report.start_date && report.end_date
      ? `${longDay(report.start_date)} – ${longDay(report.end_date)}`
      : "Last 7 days";

  const tiles = [
    { label: "Total sales", value: totals.sales_count },
    { label: "Total revenue", value: money(totals.revenue) },
    {
      label: "Items sold",
      value: totals.items_sold,
      caption: `${report.products.length} product${
        report.products.length === 1 ? "" : "s"
      }`,
    },
    {
      label: "Average daily revenue",
      value: money(totals.average_daily_revenue),
      caption: `Across ${totals.days} day${totals.days === 1 ? "" : "s"}`,
    },
    {
      label: "Busiest day",
      value: report.busiest_day ? `${report.busiest_day.count} sales` : "—",
      caption: report.busiest_day ? longDay(report.busiest_day.day) : null,
    },
    {
      label: "Quietest day",
      value: report.quietest_day ? `${report.quietest_day.count} sales` : "—",
      caption: report.quietest_day
        ? `${longDay(report.quietest_day.day)} · days with sales only`
        : null,
    },
  ];

  return (
    <>
      <form className="row g-2 mb-3 align-items-center" onSubmit={applyFilters}>
        <div className="col-auto">
          <input
            type="date"
            className="form-control"
            aria-label="Start date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
          />
        </div>
        <div className="col-auto">
          <input
            type="date"
            className="form-control"
            aria-label="End date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
          />
        </div>
        <div className="col-auto">
          <button type="submit" className="btn btn-outline-secondary">
            Apply
          </button>
        </div>
        {filtered && (
          <div className="col-auto">
            <button
              type="button"
              className="btn btn-link px-0"
              onClick={resetFilters}
            >
              Clear
            </button>
          </div>
        )}
      </form>

      {error && (
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      )}

      {report.truncated && (
        <div className="alert alert-warning py-2" role="alert">
          That range was longer than 180 days, so the report covers the first
          180 days of it.
        </div>
      )}

      <div className="row g-3 mb-3">
        {tiles.map((tile) => (
          <div className="col-6 col-lg-4 col-xl-2" key={tile.label}>
            <div className="card shadow-sm h-100">
              <div className="card-body">
                <h3 className="mb-1">{loading ? "—" : tile.value}</h3>
                <p className="text-muted mb-0 small">{tile.label}</p>
                {!loading && tile.caption && (
                  <p className="text-muted mb-0 small">{tile.caption}</p>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <SalesCharts
        series={series}
        subtitle={subtitle}
        loading={loading}
        error={error}
        emptyMessage="No sales in this period."
      />

      <div className="card shadow-sm mt-3">
        <div className="card-body">
          <h5 className="mb-0">Products Sold</h5>
          <p className="text-muted small mb-3">{subtitle}</p>

          <div className="table-responsive">
            <table className="table table-hover align-middle mb-0">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>SKU</th>
                  <th className="text-end">Quantity</th>
                  <th className="text-end">Revenue</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan={4} className="text-center py-4">
                      Loading…
                    </td>
                  </tr>
                ) : report.products.length === 0 ? (
                  <tr>
                    <td colSpan={4} className="text-center py-4 text-muted">
                      No products sold in this period.
                    </td>
                  </tr>
                ) : (
                  report.products.map((product) => (
                    <tr key={product.product_id}>
                      <td>{product.product_name}</td>
                      <td>{product.sku}</td>
                      <td className="text-end">{product.quantity}</td>
                      <td className="text-end">{money(product.revenue)}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
