# Generated by Django 4.2.13 on 2026-08-06 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The actual amount disbursed in this payment.', max_digits=12, verbose_name='Amount Paid')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the payment was processed.', verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_BANKING', 'Mobile Banking')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('remarks', models.TextField(blank=True, help_text='Optional notes about this payment (e.g. bonus, advance, deduction reason).', verbose_name='Remarks')),
                ('employee', models.ForeignKey(help_text='The employee who received this payment.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Payment',
                'verbose_name_plural': 'Salary Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
