from decimal import Decimal

from django.db import models

from fms.actor import role_name
from fms.constraints import at_most_one_role


class SalesReport(models.Model):
    """A record of each sales report generated: who ran it, for which dates, and its totals."""

    admin = models.ForeignKey(
        "accounts.AdminProfile",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="sales_reports",
        verbose_name="Generated By (Admin)",
    )
    manager = models.ForeignKey(
        "accounts.ManagerProfile",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="sales_reports",
        verbose_name="Generated By (Manager)",
    )
    start_date = models.DateField(verbose_name="Start Date")
    end_date = models.DateField(verbose_name="End Date")
    sales_count = models.PositiveIntegerField(
        default=0,
        verbose_name="Sales Count",
    )
    items_sold = models.PositiveIntegerField(
        default=0,
        verbose_name="Items Sold",
    )
    total_revenue = models.DecimalField(
        max_digits=14,
        decimal_places=2,
        default=Decimal("0"),
        verbose_name="Total Revenue",
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Generated At",
    )

    admin_id: int | None
    manager_id: int | None

    class Meta:
        db_table = "sales_report"
        verbose_name = "Sales Report"
        verbose_name_plural = "Sales Reports"
        ordering = ["-generated_at", "-id"]
        constraints = [
            models.CheckConstraint(
                check=models.Q(start_date__lte=models.F("end_date")),
                name="sales_report_start_before_end",
            ),
            at_most_one_role("admin", "manager", "sales_report_one_role"),
        ]

    @property
    def generated_by_name(self):
        return role_name(self.admin, self.manager)

    def __str__(self):
        return f"Sales report {self.start_date} – {self.end_date} ({self.generated_at:%Y-%m-%d %H:%M})"
