# Generated by Django 4.2.16 on 2026-09-23 19:56

from django.db import migrations, models


def blank_email_to_null(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    Employee.objects.filter(email="").update(email=None)


def null_email_to_blank(apps, schema_editor):
    # Only reversible while at most one employee has no email, since the
    # unique index allows just one empty string.
    Employee = apps.get_model("employees", "Employee")
    Employee.objects.filter(email__isnull=True).update(email="")


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.RunPython(blank_email_to_null, null_email_to_blank),
    ]
